# Generated by Django 3.0.4 on 2020-08-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20200822_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alltasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='', max_length=100)),
                ('payable_amount', models.CharField(default='', max_length=100)),
                ('date_or_time_due', models.CharField(default='', max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ParentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Chores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(default='', max_length=100)),
                ('child', models.ManyToManyField(blank=True, to='users.ChildProfile')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ParentProfile')),
                ('task', models.ManyToManyField(blank=True, to='work.Alltasks')),
            ],
        ),
    ]
