# Generated by Django 3.0.4 on 2020-08-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200822_1222'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alltasks',
            new_name='Alltask',
        ),
    ]
