# Generated by Django 3.0.4 on 2020-08-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20200827_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltask',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
