# Generated by Django 3.0.4 on 2020-08-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
