# Generated by Django 3.0.4 on 2020-08-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_childprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childprofile',
            old_name='username',
            new_name='name',
        ),
    ]
