# Generated by Django 3.0.4 on 2020-08-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200822_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='username',
        ),
    ]
